### PR TITLE
fix: change resourceSummary types in all proto files and clean up node manager crate

### PR DESCRIPTION
**Pull request by EstebanBAR0N**
I need to change all functions type to i32 to match proto files definition.

This will fix errors when trying to send node resources to the scheduler in node-agent main.rs.

### CODE REVIEW

**Review by sameo — CHANGES_REQUESTED** [review]
@EstebanBAR0N You need to change the proto file and not the code. It does not make sense for e.g. `total_memory` to return an `i32`. Your proto file should use unsigned integers instead of signed ones.

**Comment by EstebanBAR0N** [comment]
I understand your point of view completely. In fact, at the beginning, I would have wanted to change all the proto files. But after thinking about it, I decided to change only my code to not brake the code of all the teams.
What do you recommend at this stage of the project? Should I change all the proto files or stay with these changes even if it doesn't make much sense?

**Comment by sameo** [comment]
> Should I change all the proto files or stay with these changes even if it doesn't make much sense?

The answer is in your question :-) Do you want to do something that does not make sense? It would not make sense, right?

Bite the bullet and fix the error, across the repo. The sooner, the better and that's no big deal btw.

**Comment by EstebanBAR0N** [comment]
Okay, I will fix that. Thank you for your return.

**Comment by EstebanBAR0N** [comment]
I changed all proto files and notified the concerned teams of this change.

**Review by sameo — APPROVED** [review]

**Pull request merged**
